[package]
name = "fondabots-lib"
version = "1.1.3"
edition = "2021"

[dependencies]
chrono = "0.4"
openssl = {version = "0.10", features = ["vendored"]}
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.6"
async-trait = "0.1"
yaml-rust2 = "0.8"